development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: etsonia_dev
  pool: 5
  username: rails_user
  password: mint06

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: etsonia_test
  pool: 5
  username: rails_user
  password: mint06

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: etsonia_production
  pool: 5
  username: rails_user
  password: mint06 